# Generated by Django 2.0.3 on 2018-05-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='arguments_against',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.ArgumentsAgainst'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='arguments_for',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.ArgumentsFor'),
        ),
    ]
