# Generated by Django 2.0.3 on 2018-05-08 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentsAgainst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.TextField(max_length=500)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('created_by', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArgumentsFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.TextField(max_length=500)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('created_by', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='created_by',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debate',
            name='arguments_against',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='debate.ArgumentsAgainst'),
        ),
        migrations.AddField(
            model_name='debate',
            name='arguments_for',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='debate.ArgumentsFor'),
        ),
    ]
