# Generated by Django 2.0.3 on 2018-05-08 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_auto_20180508_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='created_by',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
