# Generated by Django 2.0.3 on 2018-05-09 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_auto_20180508_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='arguments_against',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='arguments_for',
        ),
        migrations.AddField(
            model_name='argumentsagainst',
            name='debate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.Debate'),
        ),
        migrations.AddField(
            model_name='argumentsfor',
            name='debate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.Debate'),
        ),
    ]
