# Generated by Django 2.0.3 on 2018-05-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0009_debate_number_arguments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='number_arguments',
        ),
        migrations.AddField(
            model_name='debate',
            name='number_of_arguments',
            field=models.IntegerField(default=0),
        ),
    ]
